### PR TITLE
[BUGFIX] fix image rendering with Data URLS

### PR DESCRIPTION
**Pull request by Kanti**

### CODE REVIEW

**Comment by DubbleClick** [comment]
Will this be merged soon, so it's included when using composer?

**Comment by kriks57** [comment]
could you please merge ?

**Comment by DubbleClick** [comment]
What is happening, is this project dead or why does a basic functionality fix not get a comment or merge in over 5 months?

**Comment by Kanti** [comment]
hi all,

If you want to have the bugfix in your project, you can do that with the plugin https://github.com/cweagans/composer-patches.

Here is an example `composer.json`:
````json
{
    "require": {
        "cweagans/composer-patches": "^1.6",
        "tecnickcom/tcpdf": "^6.2"
    },
    "extra": {
        "patches": {
            "tecnickcom/tcpdf": {
                "BUG data URLS https://github.com/tecnickcom/TCPDF/pull/102" :"https://github.com/Kanti/TCPDF/commit/c375a047eab63533dccb022a6f357f4eb21862db.patch"
            }
        }
    }
}
````

I hope it helps you.

**Comment by nicolaasuni** [comment]
This library is currently in a frozen state. A new library is being built: tc-lib-pdf.
Since this PR concerns some security issue I cannot merge it at this point.

**Comment by NiklasBr** [comment]
Why @nicolaasuni why not let someone else take over so you can take your time with your new library? It has been a very long time...

**Comment by girvydas** [comment]
Why this cant be merged? It doesn't break anything.

**Comment by DubbleClick** [comment]
He's working on his other pdf library that isn't yet ready and probably won't be for another year at least. Composer patches was the solution for me.

**Comment by NiklasBr** [comment]
@DubbleClick [Composer Patches](/cweagans/composer-patches) is indeed a good project I also recommend.

That said... GitHub alone reports 5.5k other *projects* using TCPDF (which is but a small subset of actual use), I cannot for the life of me understand the refusal to not accept bug fixes like these. It has adverse effects to many. It's not like @nicolaasuni can't grant collaborator/member status to another user if he feels he has no time to inspect and merge PR:s himself.

I wonder if we can fork this to a community version because the current situation is not good for anyone. Or perhaps ask Nicola or GitHub to transfer ownership?

**Comment by NiklasBr** [comment]
@nicolaasuni Please consider https://www.codeshelter.co/projects/add/

**Pull request closed without merging**
