### PR TITLE
[PHP 8.4] Fix: Curl `CURLOPT_BINARYTRANSFER` deprecated

### PR DESCRIPTION
**Pull request by Ayesh**
The `CURLOPT_BINARYTRANSFER` PHP constant from the Curl extension was no-op since PHP 5.1, and is deprecated in PHP 8.4. This removes the constant usage to avoid the deprecation notice in PHP 8.4 and later.

Because this constant was no-op since PHP 5.1 (circa 2005), this change has no impact.

See:

 - [PHP.Watch - PHP 8.4 - Curl: CURLOPT_BINARYTRANSFER deprecated](https://php.watch/versions/8.4/CURLOPT_BINARYTRANSFER-deprecated)
 - [commit](https://github.com/php/php-src/commit/fc16285538e96ecb35d017231051f83dcbd8b55b)

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you @Ayesh 

Since the project does not support that old PHP versions, LGTM !

https://github.com/tecnickcom/TCPDF/blob/5fce932fcee4371865314ab7f6c0d85423c5c7ce/composer.json#L25

**Comment by nicolaasuni** [comment]
Please try to resolve the conflicts.

**Comment by williamdes** [comment]
Hello @Ayesh
can you please rebase this PR ?

**Comment by nicolaasuni** [comment]
Thank you.
Manually merged at: https://github.com/tecnickcom/TCPDF/pull/756

**Pull request closed without merging**
