### PR TITLE
PHP 7.4 - cannot use array offset on integers

### PR DESCRIPTION
**Pull request by fisharebest**
PHP 7.3 casts integers to strings.
PHP 7.4 throws the error `Trying to access array offset on value of type int`

### CODE REVIEW

**Comment by fisharebest** [comment]
PHP 7.4 will be released in 2 days.  Can we get this merged before then?

**Comment by DevinWalker** [comment]
Any progress on this?

**Comment by fisharebest** [comment]
@DevinWalker - FYI, I am currently using [composer-patches](https://github.com/cweagans/composer-patches) to apply this (and other) patches locally.

**Comment by DevinWalker** [comment]
Thanks @fisharebest that's helpful. I'll proceed with that until it's released.

**Pull request merged**
