### PR TITLE
check if file exists before calling unlink

### PR DESCRIPTION
**Pull request by mtreuberg**
When running a Symfony command that uses tcpdf.php, the process always returns with exit code 255. The check for `file_exists()` prevents that.

For some reason, the file is being deleted just a few lines before, see here:
```
if ($handle = @opendir(K_PATH_CACHE)) {
  while ( false !== ( $file_name = readdir( $handle ) ) ) {
    if (strpos($file_name, '__tcpdf_'.$this->file_id.'_') === 0) {
      unlink(K_PATH_CACHE.$file_name); // file is deleted here
    }
  }
  closedir($handle);
}
if (isset($this->imagekeys)) {
  foreach($this->imagekeys as $file) {
    if (strpos($file, K_PATH_CACHE) === 0) {
      @unlink($file); // error is silenced, but still exit code 255 is the result
    }
  }
}
```

I added a simple `file_exists()` to prevent this from happening.

### CODE REVIEW

**Review by gustofarbi — APPROVED** [review]

**Review by ComiR — APPROVED** [review]

**Comment by xelan** [comment]
This fix is the same as in #187, which was closed without comment. Please merge the fix, as it prevents proper cleanup and thus causes failures in PDF creation projects.

**Review by xelan — APPROVED** [review]

**Review by NiklasBr — DISMISSED** [review]

**Comment by martiitram** [comment]
We still need the fix as well, because on our local environment phpstorm detect it as a warning, and it stops when using the lib. We will appreciate if the `file_exists()` is added to the main revision.

**Review by martiitram — APPROVED** [review]

**Comment by NiklasBr** [comment]
@nicolaasuni ping :)

**Review by underkaos — APPROVED** [review]
I think that this is very useful to avoid unnecessary Warning messages. And with this PR it's easy to solve.

**Review by enginydigital — DISMISSED** [review]

**Review by martiitram — APPROVED** [review]

**Comment by williamdes** [comment]
Merged into [WarnockPDF](https://github.com/code-lts/WarnockPDF), the fork of TCPDF.
See: https://github.com/code-lts/WarnockPDF/discussions/1

**Comment by mtreuberg** [comment]
Will leave this PR open in hope it gets merged... For a little while at least

**Review by nicolaasuni — APPROVED** [review]

**Pull request merged**
