### PR TITLE
allow styles on <HR> tags

### PR DESCRIPTION
**Pull request by Chrissi2812**
Allows to pass some styles to `<hr>` tags

**Example:**
```html
<hr style="color: #ff0000; dash: 4">
```
**Render:**
image

### CODE REVIEW

**Review by nicolaasuni — CHANGES_REQUESTED** [review]
These new tag keys are not defined anywhere.
You should add at least some default values.

**Comment by Chrissi2812** [comment]
The styles are now filtered before being added, so the default values will be used.

**Review by nicolaasuni — APPROVED** [review]

**Comment by fzieris** [comment]
> The styles are now filtered before being added, so the default values will be used.

No, they are not (see issue #347). Why use these four non-standard CSS property names anyway?

**Comment by vlakoff** [comment]
The OP example shows a CSS attribute `color`, whereas the code implements an HTML attribute `fgcolor`. Which one is the proper?

**Comment by vlakoff** [comment]
Nevermind, I found the following in the code:

```
$dom[$key]['fgcolor'] = TCPDF_COLORS::convertHTMLColorToDec($dom[$key]['style']['color'], $this->spot_colors);
```

… so the `color` CSS attribute is passed to that `fgcolor` property.

**Comment by trasher** [comment]
This change seems to cause several issues. First of all, undiefined index are still occuring; the only way to fix on my side is to declare empty css rules.... Not very convenient.

But I also have another problem: many times when using an HR tag (even not styled), the output PDF texts becames "blank" (white text on white page...). This issue is difficult to reproduce; I can get it fixed removing present PR changes :/

**Pull request merged**
