### PR TITLE
Normalize Unicode strings before converting them to an array

### PR DESCRIPTION
**Pull request by sebastien-fauvel**
- Fixes PDF rendering issues with combining diacritical marks
- Depends on PECL intl >= 1.0.0 (optional)

### CODE REVIEW

**Comment by sebastien-fauvel** [comment]
@nicolaasuni please review & merge. Feel free to move the code to a static method in whatever class fits you best!

**Comment by nicolaasuni** [comment]
I am currently working on a complete refactoring of TCPDF.
The Unicode processing has been moved to a separate library:
https://github.com/tecnickcom/tc-lib-unicode

Please check if your patch is still relevant there.

**Comment by sebastien-fauvel** [comment]
Hi Nicola, could you please provide me a link to the refactored version of TCPDF, if you've already made it public? I don't know if my fix will still be needed, it depends on the usages.

**Comment by nicolaasuni** [comment]
The TCPDF itself is not yet public but the unicode and font libraries are ready:
https://github.com/tecnickcom/tc-lib-unicode-data
https://github.com/tecnickcom/tc-lib-unicode
https://github.com/tecnickcom/tc-lib-pdf-font

**Comment by sebastien-fauvel** [comment]
The fix should be ported to [`Com\Tecnick\Unicode\Convert::strToChrArr`](https://github.com/tecnickcom/tc-lib-unicode/blob/develop/src/Convert.php#L67) then. I will open a PR.

**Pull request closed without merging**
