### PR TITLE
Prevents crash and files deletion.

### PR DESCRIPTION
**Pull request by DominiqueFERET**
Added an @ in front of unlink to avoid the crash.

### CODE REVIEW

**Comment by DominiqueFERET** [comment]
Yes, it's true, but, in this case, if(is_file($file)) unlink($file); is better.

**Comment by dfontenot** [comment]
Running into this issue where http:// links to images are ending up in `$this->imagekeys` causing unlink() to crash. Needing something like this MR to fix the issue.

**Comment by DominiqueFERET** [comment]
> 
> 
> Running into this issue where http:// links to images are ending up in `$this->imagekeys` causing unlink() to crash. Needing something like this MR to fix the issue.

Thank you for this correction. You're right, it's better.

**Comment by it-can** [comment]
Also having problems with this, can anyone merge this and release a new version?

**Comment by it-can** [comment]
@nicolaasuni can you merge this ?

**Comment by doits** [comment]
:+1: this also prevent deleting files not generated by tcpdf! Otherwise it ate (=deleted) one of my .png each time a pdf was generated, this is a serious bug leading to data loss!

**Comment by NiklasBr** [comment]
ping @nicolaasuni

**Pull request merged**
