### PR TITLE
Fix TypeError: count() in PHP8

### LINKED ISSUE #555: TypeError: count() on PHP 8.0.24
Hello,

I ran into this error:
Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in vendor/tecnickcom/tcpdf/tcpdf.php:19718

// for each row
if (count($table_el['trids']) > 0) {
	unset($xmax);
}

by Calling TCPDF->closeHTMLTagHandler() through  TCPDF->writeHTMLCell()

### PR DESCRIPTION
**Pull request by NiklasBr**
Resolves #555

### CODE REVIEW

**Comment by mazuk6** [comment]
I think it will close this one as well..
https://github.com/tecnickcom/TCPDF/issues/526

**Comment by williamdes** [comment]
Can you add one example in the examples folder with the code that created this error?
This will help cover your fix

**Review by nicolaasuni — DISMISSED** [review]

**Comment by nicolaasuni** [comment]
In order to be able to merge this the license/cla must be signed.

**Comment by NiklasBr** [comment]
I can't see the CLA link which usually accompanies those PR:s.

**Review by nicolaasuni — APPROVED** [review]

**Pull request merged**
