### PR TITLE
fix: php 8.1 notices

### PR DESCRIPTION
**Pull request by jmaumene**
PHP Deprecated:  Implicit conversion from float 31.5 to int loses precision in /var/www/html/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php on line 891
PHP Deprecated:  Implicit conversion from float 3.5 to int loses precision in /var/www/html/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php on line 895

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Review by jtvanschagen — APPROVED** [review]

**Comment by jmaumene** [comment]
there is a bug with the CLA, I signed it the first day and started over several times.

**Comment by andreasvonburg** [comment]
Would be great if this could be merged.

**Comment by marinaglancy** [comment]
hi, this is a correct patch and solves the problem for us (Moodle) as well. Can it please be merged?

**Comment by williamdes** [comment]
Hi @nicolaasuni 
Would you mind having a look ?

**Pull request merged**
