### PR TITLE
Fix Array and string offset access syntax with curly braces is deprec…

### PR DESCRIPTION
**Pull request by remicollet**
…ated

For upcoming PHP 7.4

### CODE REVIEW

**Comment by remicollet** [comment]
More complete than pr #126 and #131

**Comment by arshad853** [comment]
Same issue for me after upgrading PHP5 to PHP8, Working perfectly on php5.
**Fatal error: Array and string offset access syntax with curly braces is no longer supported in ..\inc\tcpdf\tcpdf.php on line 16911**

**Comment by williamdes** [comment]
> Same issue for me after upgrading PHP5 to PHP8, Working perfectly on php5. **Fatal error: Array and string offset access syntax with curly braces is no longer supported in ..\inc\tcpdf\tcpdf.php on line 16911**

Upgrade to the latest TCPDF and it will be resolved

**Comment by arshad853** [comment]
> > Same issue for me after upgrading PHP5 to PHP8, Working perfectly on php5. **Fatal error: Array and string offset access syntax with curly braces is no longer supported in ..\inc\tcpdf\tcpdf.php on line 16911**
> 
> Upgrade to the latest TCPDF and it will be resolved

@williamdes After upgrading to 6.6.2 perfectly working, Thank you.

**Pull request merged**
