### PR TITLE
SVG added viewBox to getBarcodeSVGcode output

### PR DESCRIPTION
**Pull request by martinbourdages**
It's important to have the viewBox when manipulating the SVG in Imagick and other HTML component.

### CODE REVIEW

**Comment by williamdes** [comment]
Can you show before and after screenshots ?

**Comment by martinbourdages** [comment]
https://github.com/tecnickcom/TCPDF/pull/679/commits/1be6b31fabd45045ea9b3e080fb94712e2e0400d

**Comment by nicolaasuni** [comment]
This PR is introducing too many unrelated changes.

**Comment by nicolaasuni** [comment]
Please try to resolve the conflicts.

**Comment by nicolaasuni** [comment]
Hi, Thank you for your contribution.
The barcode implementation in this lib is buggy and not up-to-date with tc-lib-barcode.
Please use tc-lib-barcode directly and use the exported SVG from there.
Note the new tc-lib-pdf library already integrated tc-lib-barcode, just missing some features that you may not need.

**Pull request closed without merging**
