### PR TITLE
Allow for bar width reduction

### PR DESCRIPTION
**Pull request by ro0NL**
Hi,

See https://barcode-test.com/barcode-advice/bar-width-reduction/ for more information

See also https://sourceforge.net/p/tcpdf/discussion/435311/thread/e00f50f8/#756c, which ultimately led to this fix

I can confirm _BWR_ on our side is also needed to account for "press gain compensation"

We are currenly applying this patch for 2-3 years in prod, and if it could be merged upstream, well, i'd be super happy :)

Thoughts?

### CODE REVIEW

**Comment by williamdes** [comment]
Could you also add an example file in `examples` like https://github.com/tecnickcom/TCPDF/blob/main/examples/example_066.php ?

**Comment by ro0NL** [comment]
@williamdes i've updated existing example_027, which seemed best for general discoverability

`.5` as an example value should give a good impression what this option does:

image

**Review by williamdes — APPROVED** [review]
Thank you, this is really awesome!

**Comment by ro0NL** [comment]
cc @nicolaasuni (yes being a project maintainer means random ppl will ping you)

**Comment by ro0NL** [comment]
closing while #537 remains open

**Pull request closed without merging**
