### PR TITLE
SVG detection fix for inline data images

### PR DESCRIPTION
**Pull request by THenkeDE**
Fixes: #645

### CODE REVIEW

**Comment by williamdes** [comment]
Thank you!
It's important to sign the CLA
Can you add an example in examples/ folder that illustrates what you fix with this fix?

**Comment by THenkeDE** [comment]
i signed the CLA but i have no idea about any examples to add - it just fixes the detection of the image Filetype from "nothing" to "svg"

**Comment by williamdes** [comment]
> i signed the CLA but i have no idea about any examples to add

Thanks
Can you add `Fixes: #645` to your PR description ?

>  it just fixes the detection of the image Filetype from "nothing" to "svg"

Yeah okay, how can I test it and see how you fix fixes something ?

**Comment by THenkeDE** [comment]
If for example you have SVG files laying around and want to add the SVG to the HTML Code using

`$svgString = file_get_contents('yourdesired.svg');`

or alternatively the <svg...></svg> data is coming from a database, you can prepare and add it to the html string like this:

`$html = '';`

Later on you add the html to the PDF using e.g. ->writeHTML.

Without my fix the following ( Font Awesome Arrow-Down Icon) will be broken because it is not detected as SVG Image:

``

**Comment by THenkeDE** [comment]
any updates? did i miss something?

**Comment by williamdes** [comment]
> any updates? did i miss something?

Still on my todo list, this is not my project
I only give some help to ensure this project continues to live
So I need to test your work at some point

If you can write an example file in examples/ folder
For example use example 66 (composer) as a base example.
That would definitely help

**Comment by williamdes** [comment]
@nicolaasuni what do you think about this fix ?

**Comment by nicolaasuni** [comment]
Please try to resolve the conflicts.

**Comment by nicolaasuni** [comment]
Thank you.
Manually merged at: https://github.com/tecnickcom/TCPDF/pull/756

**Pull request closed without merging**
