### PR TITLE
Update tcpdf.php

### PR DESCRIPTION
**Pull request by dardoguidobono**
fix problem on trying to set array value in a string

### CODE REVIEW

**Comment by alecsammon** [comment]
Can we get this merged in - without this fix then the library fails on PHP 7.1

Aware that the project is no longer maintained - but this should be an easy patch to apply.

Thanks!

**Comment by jblotus** [comment]
yes would be nice to merge this in - for now I'm forking to deal with this issue

**Comment by amakhrov** [comment]
@nicolaasuni If you could merge and publish this fix, it would be just wonderful.

Happy Valentine's! :)

**Comment by kristian-b** [comment]
A fix for that would be very nice for me too.

**Comment by hoopyfrood** [comment]
+1

**Comment by yakobe** [comment]
Hi @nicolaasuni

**Comment by yakobe** [comment]
Hi @nicolaasuni . I believe you are the owner of this repo. Would it be possible to merge this in so we can continue to use this lib?

I understand that there is a [new version in development](https://github.com/tecnickcom/tc-lib-pdf) but there does not seem to be any documentation about how to use it or when it will be stable. Or am i looking in the wrong place?

**Comment by yakobe** [comment]
Thanks 👍

**Comment by kristian-b** [comment]
Thank you @nicolaasuni !

**Pull request merged**
